import XCTest
@testable import ExpoSugiyama

/// Golden parity suite (spec §16): runs every fixture in `fixtures/`
/// (generated by the JS reference) through the Swift port and compares
/// positions and dimensions bit-for-bit.
final class ParityTests: XCTestCase {
  func testKotlinFixturesMatchSwiftLayout() throws {
    let fixturesDir = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent() // Tests/
      .deletingLastPathComponent() // ios/
      .deletingLastPathComponent() // expo-sugiyama/
      .appendingPathComponent("fixtures")

    let fileManager = FileManager.default
    let files = try fileManager.contentsOfDirectory(
      at: fixturesDir,
      includingPropertiesForKeys: nil
    ).filter { $0.pathExtension == "json" }.sorted { $0.lastPathComponent < $1.lastPathComponent }

    XCTAssertGreaterThanOrEqual(
      files.count,
      20,
      "Fixture set incomplete: expected at least 20 fixtures in \(fixturesDir.path)"
    )

    for file in files {
      let data = try Data(contentsOf: file)
      guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        XCTFail("\(file.lastPathComponent): not a JSON object")
        continue
      }

      let nodesJSON = json["nodes"] as? [[String: Any]] ?? []
      let edgesJSON = json["edges"] as? [[String: Any]] ?? []
      let expectedOutput = json["output"] as? [String: Any] ?? [:]

      var nodes: [LayoutNode] = []
      for nodeJSON in nodesJSON {
        guard
          let id = nodeJSON["id"] as? String,
          let width = nodeJSON["width"] as? NSNumber,
          let height = nodeJSON["height"] as? NSNumber
        else {
          XCTFail("\(file.lastPathComponent): malformed node \(nodeJSON)")
          continue
        }
        nodes.append(LayoutNode(id: id, width: width.doubleValue, height: height.doubleValue))
      }

      var edges: [LayoutEdge] = []
      for edgeJSON in edgesJSON {
        guard
          let id = edgeJSON["id"] as? String,
          let source = edgeJSON["source"] as? String,
          let target = edgeJSON["target"] as? String
        else {
          XCTFail("\(file.lastPathComponent): malformed edge \(edgeJSON)")
          continue
        }
        edges.append(LayoutEdge(id: id, source: source, target: target))
      }

      var options = LayoutOptions()
      if let optionsJSON = json["options"] as? [String: Any] {
        if let rankdir = optionsJSON["rankdir"] as? String {
          options.rankdir = LayoutRankDir(rawValue: rankdir) ?? .tb
        }
        if let nodesep = optionsJSON["nodesep"] as? NSNumber { options.nodesep = nodesep.doubleValue }
        if let ranksep = optionsJSON["ranksep"] as? NSNumber { options.ranksep = ranksep.doubleValue }
        if let marginx = optionsJSON["marginx"] as? NSNumber { options.marginx = marginx.doubleValue }
        if let marginy = optionsJSON["marginy"] as? NSNumber { options.marginy = marginy.doubleValue }
        if let nodeWidth = optionsJSON["nodeWidth"] as? NSNumber { options.nodeWidth = nodeWidth.doubleValue }
        if let nodeHeight = optionsJSON["nodeHeight"] as? NSNumber { options.nodeHeight = nodeHeight.doubleValue }
        if let orderingPasses = optionsJSON["orderingPasses"] as? NSNumber {
          options.orderingPasses = orderingPasses.intValue
        }
        if let cyclePolicy = optionsJSON["cyclePolicy"] as? String {
          options.cyclePolicy = cyclePolicy == "throw" ? .throwing : .tolerant
        }
      }
      // Cycle fixtures are deliberately excluded from the golden set
      if options.cyclePolicy == .throwing { continue }

      let output = try DagreLayout.computeLayout(nodes: nodes, edges: edges, options: options)

      let expectedPositions = expectedOutput["positions"] as? [String: [String: Any]] ?? [:]
      XCTAssertEqual(
        Set(expectedPositions.keys),
        Set(output.positions.keys),
        "\(file.lastPathComponent): position key mismatch"
      )
      for (id, expected) in expectedPositions {
        let actual = output.positions[id]
        XCTAssertNotNil(actual, "\(file.lastPathComponent): missing position for \(id)")
        guard let actual = actual else { continue }
        let expectedX = (expected["x"] as? NSNumber)?.doubleValue ?? 0
        let expectedY = (expected["y"] as? NSNumber)?.doubleValue ?? 0
        XCTAssertEqual(actual.x, expectedX, accuracy: 0.0, "\(file.lastPathComponent): x of \(id)")
        XCTAssertEqual(actual.y, expectedY, accuracy: 0.0, "\(file.lastPathComponent): y of \(id)")
      }

      let expectedWidth = (expectedOutput["width"] as? NSNumber)?.doubleValue ?? 0
      let expectedHeight = (expectedOutput["height"] as? NSNumber)?.doubleValue ?? 0
      XCTAssertEqual(output.width, expectedWidth, accuracy: 0.0, "\(file.lastPathComponent): width")
      XCTAssertEqual(output.height, expectedHeight, accuracy: 0.0, "\(file.lastPathComponent): height")
    }
  }
}
